const registerContent: string =
  '<p>&nbsp;<span style="color: rgb(50,114,189);background-color: rgb(255,255,255);font-size: 20px;">Congratulations!</span>&nbsp;</p>\n<p style="margin-left:0px;"><br><span style="color: rgb(0,0,0);background-color: rgb(255,255,255);font-size: 22px;"> Your account has been Registered with us.</span><br> <br><span style="color: rgb(0,0,0);background-color: rgb(255,255,255);font-size: 15px;">            Here is your email and password to Login </span><br><br><span style="color: rgb(0,0,0);background-color: rgb(255,255,255);font-size: 15px;">            Email : {email}</span><br><span style="color: rgb(0,0,0);background-color: rgb(255,255,255);font-size: 15px;">           Temporary Password: {password}</span><br><br>             {loginButton}<br></p>\n<p><span style="color: rgb(0,0,0);background-color: rgb(255,255,255);font-size: 15px;">Thank you,</span> <br>Coinifide<br>&nbsp;</p>';
const userEnquiryMailContent: string =
  '<tr>\n<td align="center" style="font-family: \'Montserrat\', Arial, sans-serif">\n  <table style="\n    font-family: \'Montserrat\', Arial, sans-serif;\n    width: 100%;\n    " width="100%" cellpadding="0" cellspacing="0" role="presentation">\n    <tbody>\n      <tr>\n        <td style="\n      background-color: #ffffff;\n      border-radius: 4px;\n      font-family: Montserrat, -apple-system,\n      \'Segoe UI\', sans-serif;\n      font-size: 15px;\n      line-height: 24px;\n      padding: 30px 40px;\n      text-align: left;\n      color: #000000;\n    " bgcolor="rgba(255, 255, 255, var(--bg-opacity))" align="left">\n\n          <p style="\nfont-weight: 600;\nfont-size: 20px;\nmargin-top: 0;\n">\n            \n            <span\n              style="font-weight: 700; color: #3272bd;text-transform: capitalize;">Hi {name}!</span>\n          </p>\n          <p style="\nfont-weight: 600;\nfont-size: 22px;\nmargin: 0 0 20px;\ncolor: #000000;\n">\n            Your Query Submitted Successfully.\n          </p>\n          <p style="margin: 0 0 16px">\n            Here is Your query details\n          </p>\n          <p style="margin: 0 0 16px">\n            Topic : {topics}\n          </p>\n          <p style="margin: 0 0 16px">\n            Message: {message}\n          </p>\n\n          \n\n          <p style="margin: 10px 0 16px">Thank you,</p>\n\n          <p style="margin: 0 0 16px">\n            Coinified\n          </p>\n        </td>\n      </tr>';
const enquiryContent: string =
  '<tr>\n<td align="center" style="font-family: \'Montserrat\', Arial, sans-serif">\n  <table style="\n    font-family: \'Montserrat\', Arial, sans-serif;\n    width: 100%;\n    " width="100%" cellpadding="0" cellspacing="0" role="presentation">\n    <tbody>\n      <tr>\n        <td style="\n      background-color: #ffffff;\n      border-radius: 4px;\n      font-family: Montserrat, -apple-system,\n      \'Segoe UI\', sans-serif;\n      font-size: 15px;\n      line-height: 24px;\n      padding: 30px 40px;\n      text-align: left;\n      color: #000000;\n    " bgcolor="rgba(255, 255, 255, var(--bg-opacity))" align="left">\n\n          <p style="\nfont-weight: 600;\nfont-size: 20px;\nmargin-top: 0;\n">\n            \n            <span\n              style="font-weight: 700; color: #3272bd;text-transform: capitalize;"></span>\n          </p>\n          <p style="\nfont-weight: 600;\nfont-size: 22px;\nmargin: 0 0 20px;\ncolor: #000000;\ntext-transform: capitalize;\n">\n             {name}-has sent a message \n          </p>\n        \n          <p style="margin: 0 0 16px">\n            Topic : {topics}\n          </p>\n          <p style="margin: 0 0 16px">\n            Message: {message}\n          </p>\n          <p style="margin: 0 0 16px">\n          User Email: {email} \n         </p>\n          <p style="margin: 10px 0 16px">User contact Number is :- {mobileNumber},</p>\n          <p style="margin: 10px 0 16px">Thank you.</p>\n        </td>\n      </tr>';
const forgotPasswordContent: string =
  '<p><br><span style="color: rgb(0,0,0);background-color: rgb(255,255,255);font-size: 20px;">            Hello </span> <span style="color: rgb(50,114,189);background-color: rgb(255,255,255);font-size: 20px;">{fullName}</span><span style="color: rgb(0,0,0);background-color: rgb(255,255,255);font-size: 20px;">,</span></p>\n<p><br><span style="color: rgb(0,0,0);background-color: rgb(255,255,255);font-size: 22px;">            Reset Your Password!          </span>&nbsp;</p>\n<p><br><span style="color: rgb(0,0,0);background-color: rgb(255,255,255);font-size: 15px;">            We received a request to reset your Coinfied</span><br><span style="color: rgb(0,0,0);background-color: rgb(255,255,255);font-size: 15px;">            account’s password.          </span>&nbsp;</p>\n<p><br><span style="color: rgb(0,0,0);background-color: rgb(255,255,255);font-size: 15px;">            To create a new password, click the link below.</span></p>\n<p><br>{forgetPasswordButton}</p>\n<p><br><span style="color: rgb(0,0,0);background-color: rgb(255,255,255);font-size: 15px;">            Disregard this e-mail if you did not request a  password change.</span><br> <br><span style="color: rgb(0,0,0);background-color: rgb(255,255,255);font-size: 15px;">            Please </span><a href="mailto:questions@coinifide.com" target="_self"><span style="color: rgb(50,114,189);background-color: rgb(255,255,255);font-size: 15px;"><strong>contact us</strong></span></a> <span style="color: rgb(0,0,0);background-color: rgb(255,255,255);font-size: 15px;">if you have questions or need assistance.</span></p>\n<p></p>\n<p style="margin-left:0px;"><span style="color: rgb(0,0,0);background-color: rgb(255,255,255);font-size: 15px;">Thank you,</span> <br>Coinifide<br>&nbsp;</p>';
const emailChangesContent: string =
  '<p>&nbsp;<br><span style="color: rgb(0,0,0);background-color: rgb(255,255,255);font-size: 20px;">            Hello</span><br> <span style="color: rgb(50,114,189);background-color: rgb(255,255,255);font-size: 20px;">{fullName}</span><span style="color: rgb(0,0,0);background-color: rgb(255,255,255);font-size: 20px;">,</span><br> <br><span style="color: rgb(0,0,0);background-color: rgb(255,255,255);font-size: 22px;">            Your Email is Changed By Admin!</span></p>\n<p style="margin-left:0px;"><br><span style="color: rgb(0,0,0);background-color: rgb(255,255,255);font-size: 15px;">            Old Email:- {oldEmail}.</span><br> <br><span style="color: rgb(0,0,0);background-color: rgb(255,255,255);font-size: 15px;">            New Email:- {newEmail}.</span><br> <br><span style="color: rgb(0,0,0);background-color: rgb(255,255,255);font-size: 15px;">            To login with new email, click the link below.</span><br><br>{coinfiedLoginButton}</p>\n<p style="margin-left:0px;">&nbsp;<br><span style="color: rgb(0,0,0);background-color: rgb(255,255,255);font-size: 15px;">            Use this credentials to login into your Talentlms account.</span><br> <br><span style="color: rgb(0,0,0);background-color: rgb(255,255,255);font-size: 15px;">            Email:- {newEmail}.</span><br> <br><span style="color: rgb(0,0,0);background-color: rgb(255,255,255);font-size: 15px;">            Password:- {password}.</span><br>&nbsp;</p>\n<p>{talentLmsLoginButton}</p>\n<p style="margin-left:0px;"><br><span style="color: rgb(0,0,0);background-color: rgb(255,255,255);font-size: 15px;">            Disregard this e-mail if you did not request a email change.</span><br> <br><span style="color: rgb(0,0,0);background-color: rgb(255,255,255);font-size: 15px;">            Please</span><br> <a href="mailto:questions@coinifide.com" target="_self"><span style="color: rgb(50,114,189);background-color: rgb(255,255,255);font-size: 15px;"><strong>contact us</strong></span></a><br><span style="color: rgb(0,0,0);background-color: rgb(255,255,255);font-size: 15px;">            if you have questions or need assistance.</span><br>&nbsp;</p>\n<p style="margin-left:0px;"><span style="color: rgb(0,0,0);background-color: rgb(255,255,255);font-size: 15px;">Thank you,</span>&nbsp;</p>\n<p style="margin-left:0px;"><br><span style="color: rgb(0,0,0);background-color: rgb(255,255,255);font-size: 15px;">            Coinifide</span><br>&nbsp;</p>';
const paymentLinkContent: string =
  '<p>&nbsp;<br><span style="color: rgb(0,0,0);background-color: rgb(255,255,255);font-size: 20px;">            Hello </span> <span style="color: rgb(50,114,189);background-color: rgb(255,255,255);font-size: 20px;">{fullName}</span><span style="color: rgb(0,0,0);background-color: rgb(255,255,255);font-size: 20px;">,</span></p>\n<p><br><span style="color: rgb(0,0,0);background-color: rgb(255,255,255);font-size: 22px;">            Payment Link To Get Your Certificate!        </span>&nbsp;</p>\n<p><br><span style="color: rgb(0,0,0);background-color: rgb(255,255,255);font-size: 15px;">            We have received a request to your Certificate for {courseName}.          </span>&nbsp;</p>\n<p><br><span style="color: rgb(0,0,0);background-color: rgb(255,255,255);font-size: 15px;">            This link will expired in {expireDate}         </span>&nbsp;</p>\n<p><br><span style="color: rgb(0,0,0);background-color: rgb(255,255,255);font-size: 15px;">            To get a Certificate, click the  \'Pay now\' button  below .</span><br>&nbsp;</p>\n<p>{certificatePaymentButton}</p>\n<p><br><span style="color: rgb(0,0,0);background-color: rgb(255,255,255);font-size: 15px;">            Disregard this e-mail if you did not request for certificate.</span><br><span style="color: rgb(0,0,0);background-color: rgb(255,255,255);font-size: 15px;">            </span><br><span style="color: rgb(0,0,0);background-color: rgb(255,255,255);font-size: 15px;">            Please</span><br> <a href="mailto:questions@coinifide.com" target="_self"><span style="color: rgb(50,114,189);background-color: rgb(255,255,255);font-size: 15px;"><strong>contact us</strong></span></a><br><span style="color: rgb(0,0,0);background-color: rgb(255,255,255);font-size: 15px;">            if you have questions or need assistance.</span><br>&nbsp;</p>\n<p style="margin-left:0px;"><span style="color: rgb(0,0,0);background-color: rgb(255,255,255);font-size: 15px;">Thank you,</span> <br><span style="color: rgb(0,0,0);background-color: rgb(255,255,255);font-size: 15px;">           Coinifide</span><br>&nbsp;</p>';

const paymentSuccess: string =
  '<p>&nbsp;<br><span style="color: rgb(98,98,98);background-color: rgb(255,255,255);font-size: 18px;">            Hey </span><span style="color: rgb(98,98,98);background-color: rgb(255,255,255);font-size: 20px;"> {name}!</span><br> <br><span style="color: rgb(38,50,56);background-color: rgb(255,255,255);font-size: 20px;">            Thank You for Purchasing! You paid for amount ${amount}</span><br> <br><span style="color: rgb(98,98,98);background-color: rgb(255,255,255);font-size: 14px;">Email Address:  {email} </span>&nbsp;</p>\n<p style="margin-left:0px;"><span style="color: rgb(98,98,98);background-color: rgb(255,255,255);font-size: 14px;">Login URL:</span> <a href="#" target="_self"><span style="color: rgb(50,114,189);background-color: rgb(255,255,255);font-size: 14px;"> www.coinfied.com </span></a>&nbsp;</p>\n<p style="margin-left:0px;"><br><span style="color: rgb(98,98,98);background-color: rgb(255,255,255);font-size: 14px;">If you did not sign up to Coinifide, please ignore this email or contact us at </span> <a href="#" target="_self"><span style="color: rgb(50,114,189);background-color: rgb(255,255,255);font-size: 14px;">questions@coinifide.com</span></a><span style="color: rgb(50,114,189);background-color: rgb(255,255,255);font-size: 14px;">.</span></p>';
export {
  registerContent,
  forgotPasswordContent,
  paymentSuccess,
  paymentLinkContent,
  enquiryContent,
  userEnquiryMailContent,
  emailChangesContent,
};
