import express from 'express';
import UserRouter from './user';
import AuthRouter from './auth';
import EmailTemplateRouter from './emailTemplate';
import FaqRouter from './faq';
import BlogCategoryRouter from './blogCategory';
import BlogRouter from './blog';
import EnterpriseRouter from './enterprise';
import CourseRouter from './course';
import ModuleRouter from './module';
import DashboardRouter from './dashboard';
import CourseTopicRouter from './courseTopic';
import PromoRouter from './promo';
import PressReleaseCategoryRouter from './pressReleaseCategory';
import PressReleaseRouter from './pressRelease';
import TransactionRouter from './transaction';
import ReportRouter from './report';
import CertificateRequestRouter from './certificateRequest';
import SettingRouter from './setting';
import TalentRouter from './talentlms';
import CorporateRouter from './corporate';
import UniversityRouter from './university';
import PrivacyPolicyRouter from './privacyPolicy';
import TermsAndConditionRouter from './termsAndCondition';
import RefundPolicyRouter from './refundPolicy';
import DoNotSellRouter from './doNotSell';
import AdminRouter from './admin';
import TeamRouter from './team';
import CmsRouter from './cms';
import MarketRouter from './marketing';
import LabRouter from './labs';

const router: express.Router = express.Router();

router.use('/auth', AuthRouter);
router.use('/user', UserRouter);
router.use('/email-templates', EmailTemplateRouter);
router.use('/faq', FaqRouter);
router.use('/blog-category', BlogCategoryRouter);
router.use('/blog', BlogRouter);
router.use('/enterprise', EnterpriseRouter);
router.use('/course', CourseRouter);
router.use('/module', ModuleRouter);
router.use('/dashboard', DashboardRouter);
router.use('/course-topic', CourseTopicRouter);
router.use('/promo-code', PromoRouter);
router.use('/press-release-category', PressReleaseCategoryRouter);
router.use('/press-release', PressReleaseRouter);
router.use('/transaction', TransactionRouter);
router.use('/report', ReportRouter);
router.use('/certificate-request', CertificateRequestRouter);
router.use('/setting', SettingRouter);
router.use('/talent-lms', TalentRouter);
router.use('/corporate', CorporateRouter);
router.use('/university', UniversityRouter);
router.use('/privacy-policy', PrivacyPolicyRouter);
router.use('/terms-and-condition', TermsAndConditionRouter);
router.use('/refund-policy', RefundPolicyRouter);
router.use('/do-not-sell', DoNotSellRouter);
router.use('/admin', AdminRouter);
router.use('/team', TeamRouter);
router.use('/cms', CmsRouter);
router.use('/market-content', MarketRouter);
router.use('/lab', LabRouter);

export default router;
