import express from 'express';
import UserRouter from './user';
import AuthRouter from './auth';
import FaqRouter from './faq';
import EnterpriseRouter from './enterprise';
import CourseTopicRouter from './courseTopic';
import CourseRouter from './course';
import BlogCategoryRouter from './blogCategory';
import BlogRouter from './blog';
import PressReleaseCategoryRouter from './pressReleaseCategory';
import PressReleaseRouter from './pressRelease';
import TransactionRouter from './transaction';
import ModuleRouter from './module';
import CertificateRequest from './certificate';
import DashboardRouter from './dashboard';
import TalentRouter from './talentlms';
import NewsLetterRouter from './newsLetter';
import SettingRouter from './setting';
import PrivacyPolicyRouter from './privacyPolicy';
import TermsAndConditionRouter from './termsAndCondition';
import RefundPolicyRouter from './refundPolicy';
import DoNotSellRouter from './doNotSell';
import TeamRouter from './team';
import CmsRouter from './cms';
import MarketRouter from './marketing';
const router: express.Router = express.Router();

router.use('/user', UserRouter);
router.use('/auth', AuthRouter);
router.use('/faq', FaqRouter);
router.use('/enterprise', EnterpriseRouter);
router.use('/course-topic', CourseTopicRouter);
router.use('/course', CourseRouter);
router.use('/blog-category', BlogCategoryRouter);
router.use('/blog', BlogRouter);
router.use('/press-release-category', PressReleaseCategoryRouter);
router.use('/press-release', PressReleaseRouter);
router.use('/transaction', TransactionRouter);
router.use('/module', ModuleRouter);
router.use('/certificate-request', CertificateRequest);
router.use('/dashboard', DashboardRouter);
router.use('/talentLms', TalentRouter);
router.use('/news-letter', NewsLetterRouter);
router.use('/setting', SettingRouter);
router.use('/privacy-policy', PrivacyPolicyRouter);
router.use('/terms-and-condition', TermsAndConditionRouter);
router.use('/refund-policy', RefundPolicyRouter);
router.use('/do-not-sell', DoNotSellRouter);
router.use('/cms', CmsRouter);
router.use('/team', TeamRouter);
router.use('/market-content', MarketRouter);

export default router;
